export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST';
export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const REQUEST_SHOPPING_LIST = 'REQUEST_SHOPPING_LIST';
export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const EDIT_SHOPPING_LIST = 'EDIT_SHOPPING_LIST';
export const DELETE_SHOPPING_LIST = 'DELETE_SHOPPING_LIST';

export const CREATE_SHOPPING_LIST_ITEM = 'CREATE_SHOPPING_LIST_ITEM';
export const GET_SHOPPING_LIST_ITEMS = 'GET_SHOPPING_LIST_ITEMS';
export const EDIT_SHOPPING_LIST_ITEM = 'EDIT_SHOPPING_LIST_ITEM';
export const DELETE_SHOPPING_LIST_ITEM = 'DELETE_SHOPPING_LIST_ITEM';
